export default function(){
    return[
        {
            id:1,
            first:'Ankit',
            last:'Gupta',
            age:23
        },
        {
            id:2,
            first:'Farhan',
            last:'yadav',
            age:24
        },
        {
            id:3,
            first:'mohan',
            last:'singh',
            age:25
        },
        {
            id:4,
            first:'Himanshu',
            last:'Pandey',
            age:26
        },
    ]
}